ran-isenberg/serverless-python-demo

.github/ISSUE_TEMPLATE/maintenance.yml, .github/workflows/serverless-service.yml, poetry.toml
Uses new `dev` environment secret for AWS OIDC and Codecov
=> chore(ci): use environment secrets over std secrets

.flake8, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/serverless-service.yml, .gitignore, .isort.cfg, Makefile, Makefile_windows, infrastructure/product/utils.py, package-lock.json, package.json, pyproject.toml
closes #21 #31 #34
This PR ensures the main workflow only runs upon source, infra, or deps changes. It also applies [hardens security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions), and make local as well as CI runs deterministic.
Breakdown of all tasks below (kept most changes with each commit except the last ones)
=> chore(ci): cleanup gha workflow, makefile, security improvements

docs/examples/domain_pillar/crud/lean_handler.py, docs/examples/integration_pillar/crud/impl.py, docs/examples/testing_pillar/crud/e2e_test_create_order_bad_flow.py, docs/examples/testing_pillar/crud/e2e_test_create_order_good_flow.py, docs/examples/testing_pillar/crud/integration_test_create_product_good_flow.py, docs/examples/testing_pillar/crud/integration_test_create_product_mocks.py, tests/e2e/crud/test_create_product.py
[
sync docs with code
<details>
Checklist:
</details>
=> chore: sync docs with code

.github/workflows/serverless-service.yml, docs/index.md, infrastructure/product/service_stack.py, mkdocs.yml
fix eventbridge bus const id with changing id per branch /user name
fix mkdocs missing homepage bug
add auto publish to github pages after main tests pass
<details>
Checklist:
</details>
=> fix: fix broken main, add automatic github oages publish

tests/e2e/crud/test_create_product.py, tests/e2e/crud/test_delete_product.py, tests/e2e/crud/test_get_product.py, tests/integration/crud/test_create_product.py, tests/integration/crud/test_delete_product.py, tests/integration/crud/test_get_product.py, tests/integration/crud/test_list_products.py, tests/unit/crud/test_create_product_input.py, tests/unit/crud/test_create_product_output.py, tests/unit/crud/test_dal_schema.py, tests/unit/crud/test_get_product_output.py, tests/unit/crud/test_product_id.py, tests/unit/crud/test_product_path_parms_input.py
add given when then to all tests 
<details>
Checklist:
</details>
=> docs: fix test documentation

docs/examples/domain_pillar/crud/handler_does_it_all.py, docs/examples/integration_pillar/crud/domain.py, docs/examples/integration_pillar/crud/impl.py, docs/examples/testing_pillar/crud/e2e_test_create_order_bad_flow.py, docs/examples/testing_pillar/crud/integration_test_create_product_mocks.py, product/crud/domain_logic/create_product.py, product/crud/integration/dynamo_db_handler.py, tests/integration/crud/test_create_product.py, tests/integration/crud/test_delete_product.py, tests/integration/crud/test_get_product.py, tests/integration/crud/test_list_products.py
update docs and minor renames
<details>
Checklist:
</details>
=> chore: update docs and minor renames

docs/decision_log.md, package-lock.json, package.json, poetry.lock, pyproject.toml
add monitoring docs and poetry update
<details>
Checklist:
</details>
=> docs: add monitoring docs

.github/workflows/main-serverless-service.yml, .github/workflows/pr-serverless-service.yml, app.py, infrastructure/product/service_stack.py, infrastructure/product/stream_processor_testing_construct.py, infrastructure/product/utils.py, tests/infrastructure/test_cdk.py
add staging and production environments
<details>
Checklist:
</details>
=> feature: implement new environments : staging and production

.github/workflows/main-serverless-service.yml
<details>
Checklist:
</details>
=> fix: fix staging and prod cicd

.github/workflows/main-serverless-service.yml, infrastructure/product/service_stack.py
<details>
Checklist:
</details>
=> fix: fix main cicd

.github/workflows/main-serverless-service.yml
<details>
Checklist:
</details>
=> fix: fix prod running with staging and not after

.github/workflows/main-serverless-service.yml, app.py, infrastructure/product/service_stack.py, tests/infrastructure/test_cdk.py
<details>
Checklist:
</details>
=> fix: fix main pipeline

.github/workflows/main-serverless-service.yml
<details>
Checklist:
</details>
=> fix: fix get stack output in tests

docs/decision_log.md, docs/examples/integration_pillar/crud/impl.py, docs/index.md, package-lock.json, package.json, poetry.lock, product/crud/integration/dynamo_db_handler.py, product/models/products/product.py, tests/integration/conftest.py, tests/integration/crud/test_create_product.py
add db timestamp to entry
<details>
Checklist:
</details>
=> chore: add timestamp

README.md
<details>
Checklist:
</details>
=> docs: Update README.md add doc link

.github/workflows/main-serverless-service.yml, .github/workflows/pr-serverless-service.yml, docs/opensource.md, docs/pipeline.md
fix loose ends - remove yapf/isort/flake8
<details>
Checklist:
</details>
=> docs: fix loose ends - remove yapf/isort/flake8

Makefile, infrastructure/product/crud_monitoring.py
add kms removal policy
<details>
Checklist:
</details>
=> fix: add kms removal policy

infrastructure/product/identity_provider_construct.py
<details>
Checklist:
</details>
=> fix : fix prod cognito

package-lock.json, package.json, poetry.lock
update deps
<details>
Checklist:
</details>
=> chore: update deps

.pre-commit-config.yaml, package-lock.json, package.json, poetry.lock
<details>
Checklist:
</details>
=> chore: poetry update

tests/crud_utils.py
<details>
Checklist:
</details>
=> fix: wrong field in api gw event

infrastructure/product/crud/identity_provider_construct.py
<details>
Checklist:
</details>
=> fix: fix deleted key by mistake
